name: (staging) Build and deploy to firebase project

on:
  workflow_dispatch:
    inputs:
      services:
        description: List services to deploy, comma separated, for example "hosting,storage,firestore,database,functions"
        required: true
        type: string

jobs:
  build_and_deploy:
    uses: psgamer/sample-project/.github/workflows/build_and_deploy_to_firebase_project_base.yml@staging
    with:
      services: ${{ inputs.services }}
      environment: staging
      build_env_command: build_staging
      project: project-sample-8e517
    secrets: inherit
