name: Build and deploy to firebase prod-test channel

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    uses: psgamer/sample-project/.github/workflows/build_and_deploy_to_firebase_channel_base.yml@master
    with:
      environment: production
      build_env_command: build_prod
      projectId: project-sample-prod
      channelId: prod-test
    secrets:
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_SAMPLE_PROD }}
