name: (base) Build and Deploy to Firebase channel

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      build_env_command:
        required: true
        type: string
      projectId:
        required: true
        type: string
      channelId:
        required: true
        type: string
    secrets:
      firebaseServiceAccount:
        required: true

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - run: npm ci
      - run: npm run ${{ inputs.build_env_command }}
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  deploy_preview_channel:
    needs: build_project
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.firebaseServiceAccount }}
          projectId: ${{ inputs.projectId }}
          channelId: ${{ inputs.channelId }}
