name: Build and deploy to firebase staging channel

on:
  push:
    branches:
      - master

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist # This is the name of the artifact
          path: dist/project-sample # This is the path to your build artifacts
  deploy_to_firebase:
    needs: build_project
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_SAMPLE_8E517 }}
          projectId: project-sample-8e517
          channelId: staging
