name: (staging) Build and deploy to firebase channel

on:
  push:
    branches:
      - staging

jobs:
  build_and_deploy:
    uses: psgamer/sample-project/.github/workflows/build_and_deploy_to_firebase_channel_base.yml@staging
    with:
      environment: staging
      build_env_command: build_staging
      projectId: project-sample-8e517
      channelId: staging
    secrets:
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_SAMPLE_8E517 }}
