name: Build project

on:
  push:
    branches:
      - master

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Install Dependencies & Build
      - run: npm ci && npm run build
